### ISSUE TITLE
Non-ASCII file names crash photoframe

### ISSUE THREAD

**Issue by dadr** [mrworf/photoframe#118] opened 2019-09-01 14:10 UTC
If photoframe encounters a filename with Unicode characters it crashes.  (typically diacritical marks or foreign language letters, like the third letter in mañana) 
The browser manager stalls at the waiting animated loop.  If you try to reload that page it says, "Problems loading /service/list from backend, please reload."
It's easy to reproduce, just rename a photo to include such a letter.

Also, this is rarely going to be a problem for web-fetched images, because Unicode is not allowed in URLs.

And finally, if running  frame.py --debug, then the console sees the following clues:

2019-09-01 10:00:30,290 - DEBUG - Displaying new image
2019-09-01 10:00:30,296 - DEBUG - USB-Photos
2019-09-01 10:00:30,301 - DEBUG - keyword: 0; index: 0
2019-09-01 10:00:30,313 - INFO - Interim saving of memory every 20 entries
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/photoframe/modules/slideshow.py", line 274, in presentation
    result = self.services.servicePrepareNextItem(cacheFolder, self.supportedFormats, displaySize, randomize)
  File "/root/photoframe/modules/servicemanager.py", line 397, in servicePrepareNextItem
    svc = self.chooseService(randomize)
  File "/root/photoframe/modules/servicemanager.py", line 352, in chooseService
    availableServices = self.getServices(readyOnly=True)
  File "/root/photoframe/modules/servicemanager.py", line 320, in getServices
    if readyOnly and self.getServiceState(k) != 'READY':
  File "/root/photoframe/modules/servicemanager.py", line 262, in getServiceState
    state = svc.updateState()
  File "/root/photoframe/services/svc_usb.py", line 115, in updateState
    return BaseService.updateState(self)
  File "/root/photoframe/services/base.py", line 132, in updateState
    elif self.getNumImages() == 0:
  File "/root/photoframe/services/base.py", line 172, in getNumImages
    images = self.getImagesFor(keyword)
  File "/root/photoframe/services/svc_usb.py", line 237, in getImagesFor
    images = self.getAlbumInfo(os.path.join(self.baseDir, keyword), files)
  File "/root/photoframe/services/svc_usb.py", line 250, in getAlbumInfo
    "mimetype": helper.getMimeType(fullFilename),
  File "/root/photoframe/modules/helper.py", line 103, in getMimeType
    mimetype = output.lstrip(filename+":").strip()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 28: ordinal not in range(128)

**Comment by mrworf** [comment] 2019-09-04 17:24
Ah, yes, USB stick would allow for non-ascii characters. It's on the list of things to fix since originally this was not a concern for google photos

**Comment by mrworf** [comment] 2019-09-21 04:56
Should be solved by latest update which will automatically install within 24hrs

**Comment by mrworf** [comment] 2019-09-30 04:08
Closing the issue since I'm no longer able to reproduce it

**Closed by mrworf** 2019-09-30 04:08 UTC

**Comment by dadr** [comment] 2019-09-30 19:20
Looks good from my units too.
